CC       = gcc
CFLAGS   = -c -g -O2 -DUNIX -I./h -I..
LFLAGS   = -s -L../fidoconf -L../smapi

OBJS    = sortarea.o purgearea.o packarea.o linkarea.o hptutil.o
SRC_DIR = src/

all: $(OBJS) \
	hptutil

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $(SRC_DIR)$*.c

hptutil: $(OBJS)
	$(CC) $(LFLAGS) -o hptutil $(OBJS) -lsmapisun -lfidoconfigsun

clean:
	-rm -f *.o
	-rm -f *~
	-rm -f hptutil
	-rm -f core
